eureka:
  client:
    healthcheck:
      enable: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: '10'
    lease-renewal-interval-in-seconds: '2'
    prefer-ip-address: 'true'