eureka:
  client:
    healthcheck:
      enable: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: '10'
    lease-renewal-interval-in-seconds: '2'
    prefer-ip-address: 'true'
spring:
  sleuth:
    #采样率-以请求百分比的方式配置和收集跟踪信息,默认值0.1(10%)
    sampler:
      percentage: 1
    # 开启feign 追踪
    feign:
      enabled: true
  # zipkin服务器
  zipkin:
    base-url: http://localhost:8883
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000